name: cat_wallpaper_app
description: Tugas 14 Flutter - Integrasi Public API (WallPaper Kucing) & Parsing JSON
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter:
    sdk: flutter
  geocoding: ^5.0.0
  geolocator: ^14.0.3
  google_maps_flutter: ^2.18.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
